services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecopoints-api
    restart: on-failure:3
    ports:
      - "${APP_PORT:-8092}:${APP_PORT:-8092}"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    environment:
      - APP_ENV=production
